#!/usr/bin/env perl
#
# $Id: yaml2xml,v 1.10 2012/01/13 06:57:15 ryo Exp $
#
# Copyright(c) 2009 Ryo SHIMIZU <ryo@misakimix.org>
#

use strict;
use warnings;
use LWP::Simple;
use XML::Simple;
use YAML::Syck;

if ($#ARGV >= 0) {
	for my $file (@ARGV) {
		print "== $file ==\n" if ($#ARGV > 0);
		yaml2xml(scalar(fileread($file)));
	}
} else {
	my $file = join("", <>);
	yaml2xml($file);
}
exit;

sub yaml2xml {
	my $yaml = shift;
	my $data = Load($yaml);
	print XMLout($data);
}

sub fileread {
	my $file = shift;

	if ($file =~ m#^(http|https|ftp)://#i) {
		my $yaml = get($file);
		unless (defined $yaml) {
			warn "$file: error\n";
			$yaml = '';
		}
		$yaml;
	} else {
		open my $fh, "<", $file or die "open: $file: $!\n";
		local $/;
		undef $/;
		<$fh>;
	}
}
